### ISSUE TITLE
renku_aqs breaks renku installation for python 3.10  and python 3.8

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/renku-aqs#65]
From a fresh virtual environment running python 3.10, I installed renku 2.2.0 and then renku_aqs.

After installing the plugin, renku is giving this error that prevents any further use. I have to redo the virtualenv to get rid of the issue.

renku --version
WARNING:nb2workflow.ontology:unable to import odakb.sparql (No module named 'odakb') but proceeding anyway
WARNING:nb2workflow.ontology:unable to import owlready2: No module named 'owlready2'
Traceback (most recent call last):
  File "/home/ferrigno/.venv/renkuVE/bin/renku", line 5, in <module>
    from renku.ui.cli import cli
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renku/ui/cli/__init__.py", line 99, in <module>
    from renku.ui.cli.dataset import dataset
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renku/ui/cli/dataset.py", line 825, in <module>
    @add_provider_options()
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renku/ui/cli/dataset.py", line 808, in add_provider_options
    providers = [p for p in ProviderFactory.get_add_providers() if p.get_add_parameters()]  # type: ignore
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renku/core/dataset/providers/factory.py", line 49, in get_add_providers
    return [p for p in ProviderFactory.get_providers() if issubclass(p, AddProviderInterface)]
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renku/core/dataset/providers/factory.py", line 43, in get_providers
    providers = get_supported_dataset_providers()
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renku/core/plugin/dataset_provider.py", line 43, in get_supported_dataset_providers
    pm = get_plugin_manager()
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renku/core/plugin/pluginmanager.py", line 41, in get_plugin_manager
    pm.load_setuptools_entrypoints("renku")
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renkuaqs/__init__.py", line 28, in <module>
    import renkuaqs.graph_utils as graph_utils
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renkuaqs/graph_utils.py", line 32, in <module>
    from renkuaqs.plugin import AQS
  File "/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/renkuaqs/plugin.py", line 35, in <module>
    from aqsconverters.io import AQS_DIR, COMMON_DIR
ImportError: cannot import name 'AQS_DIR' from 'aqsconverters.io' (/home/ferrigno/.venv/renkuVE/lib/python3.10/site-packages/aqsconverters/io.py)

trying to upgrade aqsconverters did not help

**Comment by volodymyrss** [comment]
this plugin is being split in two, please follow the [instructions](https://github.com/oda-hub/hugo-odahub/blob/renku-plugins-docs/content/docs/guide-development.md)
